### ISSUE TITLE
różne systemy

### ISSUE THREAD

**Issue by letarg0** [JoelQ/rgit#1]
Moim zdaniem dla większej przenosności programu warto pilnować kodowania. Wszystkie pliki binarne powinno sie czytac jako binarne. Przechowujesz je w formie napisu (string), ale nie wiesz jaka to forma ;) Spróbuj np. stworzyć repozytorium rgit-a i potem przenieśc to na maka i zobaczysz, że rózne sposoby kodowania różnie mogą to interpretować. Szczególnie jeśli jedne pliki zawieraja znaki UTF8 a inne nie.

Dodaj zatem:
.force_encoding Encoding::ASCII_8BIT
albo .force_encoding Encoding::UTF_8 dla przechowywania danych. Bo różne dziwne rzeczy mogą się dziać przy przenoszeniu danych lub liczeniu elementów.

**Comment by JoelQ** [comment]
Hi @letarg0 thanks for opening an issue. Unfortunately I don't speak the language you shared this in (Polish?). I put your text through Google Translate and it sounds like you're suggesting making this more robust by taking into account string encodings 😃 

The purpose of this repository was to learn (and teach) the ideas behind some common `git` commands. It is a companion to this article https://robots.thoughtbot.com/rebuilding-git-in-ruby. Because of this goal, many parts are naive/over-simplified.

This project is not meant for real use. As such, I think adding more robust string encoding would hurt the main purpose of this project.

I will updated the README in ab298b32f7786144e79b6312714eea6d6826afab to make the purpose of this project clearer.
